language: node_js
node_js:
  - "lts/Carbon"

addons:
  sonarcloud:
    organization: "ferzerkerx-github"
    token:
      secure:  "FFwz0M/1wlqkeNlWk0ERYPy7TthM+gTXP5efWCRuukEg0gqkQv/D/rWoN3aIDu0tZv/GJFETZDKILnpscDmFCaZb4/8iyfzS0tXj2o0IJAqJ1c7KSP8JVDb2EuCaL/vd0pwCfmGTbu0OabUXaAbNTRSbG1qze9TK6g2yvTAcmuXrYwzq/gPHTYdisfIk/lG8kBjViE+GPG25qYMEV4THpNPAHZF4XNrn0ChGI+svWh1FY1RHNF85OZCZGF4YYj+W/QWBhAt4zPwAUVTn3Of7fYtEYkJDLIE8mZhX6qncJTqfpk8oQhxYwN0650lwoP0RkkQhChom9vGqdygFZ4wzWGiK2wl6+N+w3cLIo5xm29pxsrtFQAToH+Qs4OZYOqqojaBoIlhUtD+J3LItYOtyDJ5F64/XVH+cXjBXvskCqIBOMclonKF6X04kAURWSKCyJOWW7ZACDoJ0AB4DGepMXqeaWJOwGfm/DVUym5tcbn1vHp5boeYhU2pTwATbsoy/6aIFVVnai4r83T1Vmjb7BPXI25Vqf9J8Q1sI/wQFRQ46F8JbWpHlF3B/bM58hdYLSp2MIQSKkPCW5r/CxJM6sGu1CkrD1gZuka8OR4lKDfRGxo8NnWwjwJkcfB0Iiom1DSKt6Dzs0YUXEX7Qv86/NfKn+MXP0+L7gb+XvuDEi+A="
env:
  secure:  "reFGc2D3TlNnKTMyBZiYEuGYfzfGHLS+LyVcJDlwfQ0q534Y+sxHkRgxNeM+t3bqZPXwDAkZcARru3qi2wz2dSQFgrMluNOk8NkyVm1L2D8U9bxYjQaGwE6vYObrEnrFimjPqyaFHZYe1LuuAsUqgPevtNfHa719VkfGvEieB6SGqHQIRyPw8e4rmhDSmawNtJGc+4W31euFTE+KZIjg0X7EEAYDTmPM6rAfrEPAds3iwuR1Of6tMdEFRKsgvgwLyKCtgliRTkOCxEgeI5KjDQX2MCRCf1o8mesWTXvij8Dynuo+qLnN8aHqCpXsFIZEqkNWTuAON/ZviH1adEfV/8vFniT0rNn/9sgR+y6vgMazCC+8RFing5SHu5T5q6QCTBtp8NQOneWeThh5K5uVgxtXp5uJTj+J7EEoy2fQDbQUzEASLvXGg232tbckVamUwFYl4HBWG9sF3ygYL1j8lxLhOEeLN2e90DfjsmBqkWsW1yAljYR3fMcHCFIxxA5RzrDOhSqwhwjZY0MQZUweF0a9O37qyZsKvtnMXsmOU5j92WEaF4EAJkjhxRyi9NZ8IaVMy476XfyWntRRKAsMxCbpP8RRK1+ztSUh7oTTaSIgsxwxT0pHmArfTnbM8CQHJhyOeVFSS1RRTFk3tYb5FRCPC+r/xR/Ye1S1N9Bjhhk="

cache:
  directories:
    - "node_modules"

install:
  - "yarn install"
  - "npm install -g snyk"

script:
  - "yarn build"
  - "yarn test"
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sonar-scanner; fi'

after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then snyk monitor; fi'